version: "3"

vars:
  IMAGE_NAME: nuagestudio/amazonlinuxbrew
  PLATFORM: linux/amd64 # Linuxbrew does not currently run on ARM64

tasks:
  default:
    cmds:
      - task: run

  build:
    summary: Builds the base Linuxbrew image on Amazonlinux
    vars:
    cmds:
      - >
        docker build
        --platform {{.PLATFORM}}
        --tag {{.IMAGE_NAME}}:latest
        --build-arg TIMESTAMP=`date +%s`
        .

  buildx:
    summary: Builds the base Linuxbrew image on Amazonlinux via Docker Buildx
    vars:
      PLATFORM: linux/arm64/v8,linux/amd64 # Linuxbrew does not currently run on ARM64
    cmds:
      - >
        docker buildx build
        --platform {{.PLATFORM}}
        --tag {{.IMAGE_NAME}}:latest
        --push
        --file ./Dockerfile
        --build-arg TIMESTAMP=`date +%s`
        .

  push:
    summary: Pushes the image onto the registry
    cmds:
      - docker login && docker push {{.IMAGE_NAME}}

  ci:
    summary: Simulates the Github Actions CI locally
    cmds:
      - act --platform ubuntu-latest=nuagestudio/github-actions:alpine

  run:
    vars:
      PLATFORM: linux/amd64
    cmds:
      - docker run -it --rm --platform {{.PLATFORM}} {{.IMAGE_NAME}}
