version: "3"

vars:
  IMAGE_NAME: nuagestudio/amazonlinuxbrew

tasks:
  default:
    cmds:
      - task: run

  ######################################################################################
  ### Build
  ######################################################################################

  build:
    summary: Builds the base Linuxbrew image on Amazonlinux
    cmds:
      - docker build -t {{.IMAGE_NAME}} -f ./Dockerfile .
    sources:
      - Dockerfile

  ######################################################################################
  ### Run
  ######################################################################################

  run:
    deps: [build]
    cmds:
      - "docker run -it --rm {{.IMAGE_NAME}}"
