version: "3"

vars:
  IMAGE_NAME: nuagestudio/amazonlinuxbrew
  # Note: Linuxbrew does not currently support ARM 64bit
  # https://docs.brew.sh/Homebrew-on-Linux#arm
  PLATFORM: linux/amd64

tasks:
  default:
    cmds:
      - task: run

  build:
    summary: Builds the base Linuxbrew image on Amazonlinux
    cmds:
      - >
        docker build
        --platform {{.PLATFORM}}
        --tag {{.IMAGE_NAME}}
        --file ./Dockerfile
        --build-arg TIMESTAMP=`date +%s`
        .

  push:
    summary: Pushes the image onto the registry
    cmds:
      - docker login && docker push {{.IMAGE_NAME}}

  ci:
    summary: Simulates the Github Actions CI locally
    cmds:
      - act --platform ubuntu-latest=nuagestudio/github-actions:alpine

  run:
    deps: [build]
    cmds:
      - docker run -it --rm --platform {{.PLATFORM}} {{.IMAGE_NAME}}
