FROM nuagestudio/amazonlinuxbrew

LABEL maintainer="Louis Amon <louis@nuage.studio>"

# Install Node version manager
RUN brew install nodenv

# Install Node dependency manager
RUN brew install yarn

CMD bash