FROM nuagestudio/amazonlinuxbrew

LABEL maintainer="Louis Amon <louis@nuage.studio>"

# Install Python version manager
RUN brew install pyenv

# Install Python dependency manager
RUN brew install poetry

CMD bash